[features]
unified_exec = true
web_search_request = true
skills = true
shell_snapshot = true
tui2 = true

# configuring mcp server
[mcp_servers.deepwiki]
url= "https://mcp.deepwiki.com/mcp"
# ---
[mcp_servers.langchain]
url="https://docs.langchain.com/mcp"
# ---
[mcp_servers.github]
command = "npx"
args = ["-y", "mcp-remote@latest", "https://api.githubcopilot.com/mcp", "--header", "Authorization:${GITHUB_MCP_PAT}"]
[mcp_servers.github.env]
GITHUB_MCP_PAT = "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"
# ---
[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
http_headers = { "CONTEXT7_API_KEY" = "ctx7sk-e80fd12d-c6a0-48fe-a983-9e13c3c591a1" }
# ---
